[project]
name = "resuscan-new-0604"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "boto3>=1.42.84",
    "doclayout-yolo>=0.0.4",
    "en-core-web-sm",
    "groq>=1.1.2",
    "huggingface-hub>=1.9.0",
    "nltk>=3.9.4",
    "openpyxl>=3.1.5",
    "pandas>=3.0.2",
    "pdfminer>=20191125",
    "pdfplumber>=0.11.9",
    "phonenumbers>=9.0.27",
    "pyahocorasick>=2.3.1",
    "pymupdf>=1.27.2.2",
    "python-dotenv>=1.2.2",
    "sentence-transformers>=5.4.1",
    "spacy>=3.8.14",
    "tabula>=1.0.5",
    "webcolors==1.13",
]

[tool.uv.sources]
en-core-web-sm = { url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl" }
