def remove_exact_substring_matches(dictionary):
            keys_to_remove = []
            keys = list(dictionary.keys())
            for i in range(len(keys)):
                current_key = keys[i]
                for j in range(len(keys)):
                    if i != j:  
                        other_key = keys[j]
                        if current_key in other_key:
                            keys_to_remove.append(current_key)
                            break 
            for key in keys_to_remove:
                del dictionary[key]
            return dictionary
        

def remove_exact_unwanted_Keys(data):
    to_delete = []

    for key in data:
        words = key.split()
        lengths = [len(word) for word in words]
        
        if all(length <= 3 for length in lengths):
            to_delete.append(key)
        

    for key in to_delete:
        del data[key]
    return data

def frequent_ngrams(words, n):
    try:
        
        # print(words)
        # print(f"\n🚀 Generating {n}-grams...")
    
        ngrams = [" ".join(words[i : i + n]) for i in range(len(words) - n + 1)]
        # print(f"\n🚀 Generated {len(ngrams)} {n}-grams.")
        # print(f"\n 📄 Sample {n}-grams:", ngrams[:10])


        ngram_counts = {}
        for gram in ngrams:
            ngram_counts[gram] = ngram_counts.get(gram, 0) + 1

        # print(f"\n✅ Total {n}-grams:", len(ngram_counts))

    
        frequent_ngrams = {
            gram: count
            for gram, count in ngram_counts.items()
            if count >= 2
        }

        return frequent_ngrams
    except Exception as e:
        print(f"frequent_{n}grams", str(e))
        return {}    
    

def frequent_dynamic_ngrams(text, combined_data):
    
    try:

        words = text.split()
        # print("\n📃 Original Words:", words)
        words = [word for word in words if word not in combined_data]
        # print("\n 📃 Cleaned Words:", words)
        all_frequent_ngrams = {}

        n = 4  

        while True:

            ngram_freq = frequent_ngrams(words, n)
            # print(f"\n\n 🔍 Frequent {n}-grams:", ngram_freq)
            # print(ngram_freq)
            if not ngram_freq:
                # print("No more frequent n-grams found.")
                break
            all_frequent_ngrams[f"{n}-gram"] = ngram_freq
            # print(f"Added {len(ngram_freq)} {n}-grams to all_frequent_ngrams.")
            n += 1

        merged_dict = {}
        for ngram_dict in all_frequent_ngrams.values():
            merged_dict.update(ngram_dict)

        # print("\n✅ Merged Frequent N-grams:\n", merged_dict)
        print("\nRemoving exact substring matches...")
        merged_dict1 = remove_exact_substring_matches(merged_dict)
        print("\nAfter removing exact substring matches:\n", merged_dict1)
        print("\nRemoving exact unwanted keys...")
        remove_2 = remove_exact_unwanted_Keys(merged_dict1)
        print("\nAfter removing exact unwanted keys:", remove_2)
        return remove_2
    
    except Exception as e:
        print("frequent_dynamic_ngrams", str(e))
        return {}
    

from collections import Counter

# Counter based n-gram generator
def better_frequent_ngrams(text, combined_data, min_n=2, max_n=6):
    words = [w for w in text.split() if w not in combined_data]

    counts = Counter()

    # print("\n📃 Cleaned Words for Counter-based n-grams:", words)
    for i in range(len(words)):
        for n in range(min_n, max_n + 1):
            # print(f"\n🚀 Generating {n}-gram starting at index {i}...")
            if i + n <= len(words):
                gram = " ".join(words[i:i+n])
                counts[gram] += 1

    # print("\n✅ Total n-grams generated by Counter:", len(counts))
    result = {k: v for k, v in counts.items() if v >= 2}

    result = remove_exact_substring_matches(result)
    result = remove_exact_unwanted_Keys(result)

    return result


from nltk.util import ngrams
from collections import Counter

def find_repeated_phrases(words, min_n=4, min_count=2):

    all_ngrams = Counter()
    n = min_n
    while True:
        counts = Counter(" ".join(g) for g in ngrams(words, n))
        # print(f"\n🚀 Generated {n}-grams with NLTK, total unique: {len(counts)}")
        # print(f"\n📄 Sample {n}-grams with NLTK:", list(counts.items())[:10])
        frequent = {k: v for k, v in counts.items() if v >= min_count}
        if not frequent:
            break
        all_ngrams.update(frequent)
        n += 1

    # Prune substrings: keep only longest non-contained phrases
    keys = sorted(all_ngrams, key=len, reverse=True)
    final = {}
    for k in keys:
        if not any(k in longer for longer in final):
            final[k] = all_ngrams[k]
    return final

if __name__ == "__main__":

    # ---- Sample Resume Text ----
    text = """
    Rahul Sharma | rahul@gmail.com | +91 9999999999

    Data Analyst: ABC Corp
    Jan 2022 – Dec 2023
    • Worked on data analysis and data visualization for business insights
    • Built dashboards using Power BI and data analysis tools
    • Delivered data analysis reports to stakeholders

    Senior Data Analyst: ABC Corp
    Jan 2024 – Present
    • Led data analysis and data visualization initiatives across teams
    • Built dashboards using Power BI and data analysis tools
    • Delivered data analysis reports to senior stakeholders
    """

    # ---- Simulated combined_data (noise removal) ----
    combined_data = [
        "Rahul", "Sharma", "rahul@gmail.com", "+91", "9999999999",
        "Jan", "2022", "Dec", "2023", "2024", "Present", "–", "|", "•"
    ]

    print("\n===== INPUT TEXT =====\n")
    print(text)

    print("\n===== CLEANED WORDS =====\n")
    words = text.split()
    cleaned_words = [w for w in words if w not in combined_data]
    print(cleaned_words)

    # ---- Run your function ----
    import time
    original_time = time.time()
    original_result = frequent_dynamic_ngrams(text, combined_data)
    original_time = time.time() - original_time
    print(f"\nOriginal frequent_dynamic_ngrams took {original_time:.2f} seconds.")
    counter_time = time.time()
    counter_result = better_frequent_ngrams(text, combined_data, min_n=4, max_n=14)
    counter_time = time.time() - counter_time
    print(f"\nCounter-based better_frequent_ngrams took {counter_time:.2f} seconds.")
    nltk_time = time.time()
    nltk_counter_result = find_repeated_phrases(cleaned_words, min_n=4, min_count=2)
    nltk_time = time.time() - nltk_time
    print(f"\nNLTK-based find_repeated_phrases took {nltk_time:.2f} seconds.")

    print("\n===== FINAL OUTPUT =====\n")
    print("Original frequent_dynamic_ngrams Result:\n", original_result)
    print("Counter-based Result:\n", counter_result)
    print("NLTK-based Result:\n", nltk_counter_result)